# openapi.yaml
openapi: 3.0.1
info:
  title: Testing Multi-file Bundle
  version: '1.0.0'
servers:
  - url: 'https://api.example.com'
paths:
  /users/{userId}:
    get:
      summary: Get user details
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json: # This must be on its own line indented under content
              schema:
                $ref: './models/user.yaml'
